import "./globals.css";

// import { Inter } from "next/font/google";
// ໃຊ້ Font ສຳລັບພາສາອັງກິດເທົ່ານັ້ນ
// const inter = Inter({ subsets: ["latin"] }); className={inter.className}


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
